version: '3'
services:
  bright:
    build:
      context: ./bright
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - light-network
    depends_on:
      - rabbitmq

  dark:
    build:
      context: ./dark
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - light-network
    depends_on:
      - rabbitmq
      - postgres

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - light-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: messages
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - light-network

volumes:
  pgdata:

networks:
  light-network:
    driver: bridge